services:
  auth:
    build:
      context: ./backend/auth
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://karanreddy3267:Drew-3267@cluster0.omcuk69.mongodb.net/bank_crm_auth
    depends_on:
      - mongo
  bank:
    build:
      context: ./backend/bank
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/data-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3267
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "5173:80"
    environment:
      - REACT_APP_AUTH_API_URL=http://localhost:5000
      - REACT_APP_DATA_API_URL=http://localhost:8080

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3267
      POSTGRES_DB: data-db
    ports:
      - "5432:5432"

